name: Java CI     #Actions名称

on:
  push:
    branches:
      - master       #在提交master时触发

jobs:
  build:
  runs-on: ubuntu-latest    #运行环境

steps:

  - uses: actions/checkout@master    #获取master分支
  - name: Set up JDK 1.8
    uses: actions/setup-java@v1  #使用官方脚本创建java环境
    with:
      java-version: 1.8
